server:
  port: 8100

spring:
  application:
    name: users
  config:
    import: "optional:configserver:http://localhost:8888"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/timeforge
          jwk-set-uri: http://localhost:8080/realms/timeforge/protocol/openid-connect/certs
          audiences: users
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.security: DEBUG
