server:
  port: 8222

spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/timeforge
          # Dé-commente si tu veux forcer l'audience côté gateway :
          audiences: users

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: users-service
          uri: lb://users
          predicates:
            - Path=/users/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
